/*
 * This source file was generated by the Gradle 'init' task
 */
package com.telpirion.minecraftplugin;

import org.junit.Test;
import static org.junit.Assert.*;

public class PluginTest {
    @Test public void appHasAGreeting() {
        assert true;
    }
}
